Fix async non-existing file
scottcorgan/file-exists pull request #8
Opened 2017-05-30 09:02 UTC by perry-mitchell

Previously, as in #7, non-existing files threw errors in async mode. This PR addresses that issue by checking for `ENOENT` error codes when using `fs.stat()`.

2017-05-30 09:03 UTC, perry-mitchell commented
@scottcorgan I ran the tests and they seem to work. I was able to make the tests fail by adding the check for non-existing files first, and then updated the code to fix them.

2017-05-30 10:50 UTC, scottcorgan requested changes
Thanks so much for doing this! These types of bugs get nasty!

Just one small change if ya could. Thanks!

2017-05-30 10:50 UTC, scottcorgan commented on index.js
> +        done(null, false) :
I know this feels a bit nit-picky, but can you change this to:

```js
return err.code === 'ENOENT'
  ? done(null, false)
  : done(err)
```

Also, why is it that we return `null` as the error if the file is missing?

2017-05-30 20:38 UTC, perry-mitchell commented
> I know this feels a bit nit-picky

@scottcorgan No not at all!

> Also, why is it that we return null as the error if the file is missing?

It's consistent with the following call in the file: `done(null, stats.isFile())`. Not only that, it's seen as a standard approach to callbacks for the pattern `callback(error, successValue)`. `error` is always first, and is either an `Error` instance or `null` to indicate no error. Makes checks like `if (err) return reject(err)` more practical when dealing with callback->promise situations too.

2017-06-01 14:33 UTC, scottcorgan commented
Sweet. If you can just make the one little change to the syntax style, I'll release it!

Thanks 👍

2017-06-01 15:09 UTC, perry-mitchell commented
Sorry! I missed part of your suggestion @scottcorgan - I've updated it.

2017-06-01 15:37 UTC, scottcorgan approved these changes

2017-06-01 15:37 UTC, merged

2017-06-01 15:38 UTC, scottcorgan commented
Thanks! Published as `4.0.0` (the output is changed, so it's breaking)